mongo:
  image: 'mongo:latest'
  ports:
    - '27017:27017'
nhc-api:
  build: .
  entrypoint: /go/bin/nhc-api -env=dev -init=true
  environment:
    - MONGODB_URL=mongo
  links:
    - mongo
  ports:
    - '8080:8443'
